<?php

namespace Kaadon\Encrypt;

use Kaadon\Encrypt\RSA\RSA;
use think\facade\Config;

/**
 *
 */
class TPRSA extends RSA
{
    /**
     * @var mixed|string
     */
    private $path = "../default/";

    /**
     *
     */
    public function __construct()
    {
        if (Config::has("kaadon.encrypt.path")) {
            $path = Config::get("kaadon.encrypt.path");
            if (!empty($path)) $this->path = $path;
        }
        parent::__construct();
    }

    /**
     * @param string|null $path
     * @return array
     * @throws \Exception
     */
    public static function createKey(?string $path = null): array
    {
        $selfClass = new self();
        return parent::createKey($selfClass->path); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $string
     * @param string|null $path
     * @return mixed
     * @throws \Exception
     */
    public static function decrypt(string $string, ?string $path = null)
    {
        $selfClass = new self();
        return parent::decrypt($string, $selfClass->path); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $string
     * @param string|null $path
     * @return string
     * @throws \Exception
     */
    public static function encrypt(string $string, ?string $path = null): string
    {
        $selfClass = new self();
        return parent::encrypt($string, $selfClass->path); // TODO: Change the autogenerated stub
    }
}